/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: 'class',
    content: [
        './pages/**/*.{js,ts,jsx,tsx,mdx}',
        './components/**/*.{js,ts,jsx,tsx,mdx}',
        './app/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    theme: {
        extend: {
            colors: {
                "on-primary-fixed": "#370d00",
                "primary": "#ffb59a",
                "inverse-primary": "#a73a00",
                "surface-tint": "#ffb59a",
                "inverse-surface": "#e5e2e1",
                "background": "#131313",
                "surface-bright": "#3a3939",
                "surface-container-high": "#2a2a2a",
                "error-container": "#93000a",
                "primary-fixed": "#ffdbce",
                "on-secondary-fixed-variant": "#334c44",
                "tertiary-fixed": "#d2e4ff",
                "on-tertiary-container": "#002d51",
                "secondary-container": "#334c44",
                "tertiary": "#a0c9ff",
                "secondary": "#b1ccc3",
                "secondary-fixed-dim": "#b1ccc3",
                "secondary-fixed": "#cde9df",
                "on-primary-container": "#521800",
                "on-primary": "#5a1b00",
                "surface-variant": "#353534",
                "on-tertiary-fixed": "#001c37",
                "tertiary-fixed-dim": "#a0c9ff",
                "primary-fixed-dim": "#ffb59a",
                "on-primary-fixed-variant": "#802a00",
                "on-tertiary-fixed-variant": "#00497f",
                "on-secondary-fixed": "#06201a",
                "on-error-container": "#ffdad6",
                "tertiary-container": "#0096fd",
                "on-secondary": "#1d352e",
                "primary-container": "#ff5c01",
                "surface-container-low": "#1c1b1b",
                "outline": "#ab897d",
                "surface-container": "#201f1f",
                "on-error": "#690005",
                "error": "#ffb4ab",
                "outline-variant": "#5b4137",
                "on-tertiary": "#00325a",
                "inverse-on-surface": "#313030",
                "on-secondary-container": "#a0bbb2",
                "surface-dim": "#131313",
                "surface-container-highest": "#353534",
                "surface": "#131313",
                "on-surface-variant": "#e4beb1",
                "surface-container-lowest": "#0e0e0e",
                "on-surface": "#e5e2e1",
                "on-background": "#e5e2e1",
                brand: {
                    orange: '#FF5C01',
                    dark: '#020306',
                    gray: '#B9B9B9',
                    light: '#F4F4F6',
                },
            },
            fontFamily: {
                sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
                display: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
                headline: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
                body: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
                label: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
                outfit: ['Outfit', 'sans-serif'],
            },
            fontWeight: {
                light: '300',
                normal: '400',
                medium: '500',
                semibold: '600',
                bold: '700',
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
    ],
};
