/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: 'class',
    content: [
        './pages/**/*.{js,ts,jsx,tsx,mdx}',
        './components/**/*.{js,ts,jsx,tsx,mdx}',
        './app/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    theme: {
        extend: {
            colors: {
                /* ─── DINE Brand Tokens ─────────────────────── */
                dine: {
                    primary:   '#e9463c',
                    secondary: '#212121',
                    white:     '#ffffff',
                    black:     '#191919',
                    // Shades da primária
                    '50':  '#fdf2f2',
                    '100': '#fce4e3',
                    '200': '#f9cdcb',
                    '300': '#f4a9a6',
                    '400': '#ec7470',
                    '500': '#e9463c',
                    '600': '#d42e24',
                    '700': '#b2231a',
                    '800': '#942019',
                    '900': '#7b201c',
                    '950': '#420d0a',
                },

                /* ─── Alias de compatibilidade ───────────────── */
                brand: {
                    orange: '#e9463c',  // migrado de #FF5C01
                    dark:   '#191919',
                    gray:   '#B9B9B9',
                    light:  '#F4F4F6',
                },

                /* ─── Material Design 3 (mantido) ───────────── */
                "on-primary-fixed":           "#370d00",
                "primary":                    "#e9463c",
                "inverse-primary":            "#b52e25",
                "surface-tint":               "#e9463c",
                "inverse-surface":            "#e5e2e1",
                "background":                 "#191919",
                "surface-bright":             "#3a3939",
                "surface-container-high":     "#2a2a2a",
                "error-container":            "#93000a",
                "primary-fixed":              "#ffdbce",
                "on-secondary-fixed-variant": "#334c44",
                "tertiary-fixed":             "#d2e4ff",
                "on-tertiary-container":      "#002d51",
                "secondary-container":        "#2e2e2e",
                "tertiary":                   "#a0c9ff",
                "secondary":                  "#b1ccc3",
                "secondary-fixed-dim":        "#b1ccc3",
                "secondary-fixed":            "#cde9df",
                "on-primary-container":       "#521800",
                "on-primary":                 "#ffffff",
                "surface-variant":            "#353534",
                "on-tertiary-fixed":          "#001c37",
                "tertiary-fixed-dim":         "#a0c9ff",
                "primary-fixed-dim":          "#e9463c",
                "on-primary-fixed-variant":   "#802a00",
                "on-tertiary-fixed-variant":  "#00497f",
                "on-secondary-fixed":         "#06201a",
                "on-error-container":         "#ffdad6",
                "tertiary-container":         "#0096fd",
                "on-secondary":               "#1d352e",
                "primary-container":          "#e9463c",
                "surface-container-low":      "#1c1b1b",
                "outline":                    "#ab897d",
                "surface-container":          "#212121",
                "on-error":                   "#690005",
                "error":                      "#ffb4ab",
                "outline-variant":            "#5b4137",
                "on-tertiary":                "#00325a",
                "inverse-on-surface":         "#313030",
                "on-secondary-container":     "#a0bbb2",
                "surface-dim":                "#191919",
                "surface-container-highest":  "#353534",
                "surface":                    "#191919",
                "on-surface-variant":         "#e4beb1",
                "surface-container-lowest":   "#141414",
                "on-surface":                 "#f5f5f5",
                "on-background":              "#f5f5f5",
            },
            fontFamily: {
                sans:    ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
                display: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
                headline:['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
                body:    ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
                label:   ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
                outfit:  ['Outfit', 'sans-serif'],
            },
            fontWeight: {
                light:    '300',
                normal:   '400',
                medium:   '500',
                semibold: '600',
                bold:     '700',
            },
            borderRadius: {
                '4xl': '2rem',
                '5xl': '2.5rem',
            },
            animation: {
                'pulse-slow': 'pulse 3s ease-in-out infinite',
                'fade-in':    'fadeIn 0.4s ease-out both',
            },
            keyframes: {
                fadeIn: {
                    '0%':   { opacity: '0', transform: 'translateY(8px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
    ],
};
